IF( WIN32 )

FILE(GLOB DDK_INCLUDE_PATHS_0 "C:/WinDDK/*/inc/api")
FILE(GLOB DDK_REDIST_DPINST_PATHS_0 "C:/WinDDK/*/redist/DIFx/dpinst/MultiLin")

IF( ${CMAKE_CL_64} )
	FILE(GLOB DDK_LIBRARY_PATHS_0 "C:/WinDDK/*/lib/win7/amd64")
	FILE(GLOB DDK_REDIST_DIFXAPI_PATHS_0 "C:/WinDDK/*/redist/DIFx/DIFxAPI/amd64")
ELSE( ${CMAKE_CL_64} )
	FILE(GLOB DDK_LIBRARY_PATHS_0 "C:/WinDDK/*/lib/win7/i386")
	FILE(GLOB DDK_REDIST_DIFXAPI_PATHS_0 "C:/WinDDK/*/redist/DIFx/DIFxAPI/x86")
ENDIF( ${CMAKE_CL_64} )

SET(
	DDK_INCLUDE_PATHS
	${DDK_INCLUDE_PATHS_0}
)

SET(
	DDK_LIBRARY_PATHS
	${DDK_LIBRARY_PATHS_0}
)

FIND_PATH(
	DDK_INCLUDE_DIR
	difxapi.h
	${DDK_INCLUDE_PATHS}
)

FIND_LIBRARY( DDK_DIFXAPI NAMES difxapi PATHS ${DDK_LIBRARY_PATHS} )
FIND_FILE( DIFXAPI_DLL difxapi.dll PATHS ${DDK_REDIST_DIFXAPI_PATHS_0} NO_DEFAULT_PATH )
FIND_FILE( DPINST_X86 dpinst.exe PATHS ${DDK_REDIST_DPINST_PATHS_0}/x86 NO_DEFAULT_PATH )
FIND_FILE( DPINST_X64 dpinst.exe PATHS ${DDK_REDIST_DPINST_PATHS_0}/amd64 NO_DEFAULT_PATH )

SET(
	DDK_LIBRARIES
	${DDK_DIFXAPI}
)

SET( DDK_FOUND 0 )
IF( EXISTS "${DDK_INCLUDE_DIR}" )
	SET( DDK_FOUND 1 )
	ADD_DEFINITIONS( -DHAVE_DDK )
	INCLUDE_DIRECTORIES(
		${DDK_INCLUDE_DIR}
	)
ENDIF( EXISTS "${DDK_INCLUDE_DIR}" )

ELSE( WIN32 )
	MESSAGE( WARNING "DDK is a Windows only SDK" )
ENDIF( WIN32 )
