#  Copyright (C) 2004-2009, Robotics Equipment Corporation GmbH

SET(
		INNOSETUP_FOUND 0
)

set(PROGRAMFILESX86 "PROGRAMFILES(X86)")
	
FIND_PATH(
   INNOSETUP_DIR 
   NAMES
   Compil32.exe
   PATHS
   "$ENV{${PROGRAMFILESX86}}/Inno Setup 5"
   "$ENV{ProgramFiles}/Inno Setup 5"
)

IF( INNOSETUP_DIR )
	FIND_FILE( INNOSETUP_COMPILER Compil32.exe PATHS ${INNOSETUP_DIR} )
	
	SET(
		INNOSETUP_FOUND 1
	)
	
	MARK_AS_ADVANCED(
		INNOSETUP_DIR
		INNOSETUP_FOUND
		INNOSETUP_COMPILER
	)
	
ENDIF( INNOSETUP_DIR )
