#!/bin/sh
set -e
VERSION=firmware

OLDVERSION=0
if [ -f /usr/local/OpenRobotinoAPI/1/bin/linux/ea09cmd ]; then
	OLDVERSION=1
fi

if [ "$1" = "configure" ]; then
	if [ 1 -eq $OLDVERSION ]; then
		/etc/init.d/controld.sh stop || true
	
		/usr/local/OpenRobotinoAPI/1/daemons/rtai.sh start || true
		/usr/local/OpenRobotinoAPI/1/bin/linux/ea09cmd setfpgapower 1 || true

		sleep 2
	else
		/etc/init.d/controld2.sh stop || true
		/etc/init.d/rtai.sh restart || true
		/usr/local/robotino/daemons/bin/controld2 -fpgapower 1
		
	fi

	/etc/init.d/rtai.sh stop || true
	
	modprobe 8250 || true
	sleep 2

	/usr/local/EA09/bin/lpc21isp -control -verify /usr/local/EA09/firmware/${VERSION}.hex /dev/ttyS0 115200 25000 || true
	/usr/local/EA09/bin/lpc21isp -control -verify -detectonly /usr/local/EA09/firmware/${VERSION}.hex /dev/ttyS0 115200 25000 || true
	
	/etc/init.d/rtai.sh start || true
	if [ 1 -eq $OLDVERSION ]; then
		/etc/init.d/controld.sh start || true
	else
		/etc/init.d/controld2.sh start || true
	fi
fi
