#  Copyright (C) 2004-2009, Robotics Equipment Corporation GmbH

FIND_PATH(
   RTAI_INCLUDE_DIR 
   NAMES
   rtai.h
   PATHS
   ${EXTERNAL_DIR}/rtai/include
   NO_DEFAULT_PATH
)

IF( RTAI_INCLUDE_DIR )
	SET( RTAI_FOUND TRUE )
ENDIF( RTAI_INCLUDE_DIR )

MARK_AS_ADVANCED(
	RTAI_FOUND
	RTAI_INCLUDE_DIR
) 
