#ifndef _MCB2300_H_
#define _MCB2300_H_

#define GPIO0_BIT 17
#define GPIO0_PIN IOPIN0
#define GPIO0_DIR IODIR0
#define GPIO0_SET IOSET0
#define GPIO0_CLR IOCLR0

#define GPIO1_BIT 18
#define GPIO1_PIN IOPIN0
#define GPIO1_DIR IODIR0
#define GPIO1_SET IOSET0
#define GPIO1_CLR IOCLR0

#define GPIO2_BIT 7
#define GPIO2_PIN FIO4PIN
#define GPIO2_DIR FIO4DIR
#define GPIO2_SET FIO4SET
#define GPIO2_CLR FIO4CLR

#define SUS_S3_BIT 25
#define SUS_S3_PIN IOPIN0
#define SUS_S3_DIR IODIR0
#define SUS_S3_SET IOSET0
#define SUS_S3_CLR IOCLR0

#define SUS_S4_BIT 5
#define SUS_S4_PIN FIO2PIN
#define SUS_S4_DIR FIO2DIR
#define SUS_S4_SET FIO2SET
#define SUS_S4_CLR FIO2CLR

#define SUS_S5_BIT 4
#define SUS_S5_PIN FIO2PIN
#define SUS_S5_DIR FIO2DIR
#define SUS_S5_SET FIO2SET
#define SUS_S5_CLR FIO2CLR

#define THRM_BIT 3
#define THRM_PIN FIO2PIN
#define THRM_DIR FIO2DIR
#define THRM_SET FIO2SET
#define THRM_CLR FIO2CLR

#define PWROK_BIT 20
#define PWROK_PIN IOPIN0
#define PWROK_DIR IODIR0
#define PWROK_SET IOSET0
#define PWROK_CLR IOCLR0

#define PWRBTN_BIT 21
#define PWRBTN_PIN IOPIN0
#define PWRBTN_DIR IODIR0
#define PWRBTN_SET IOSET0
#define PWRBTN_CLR IOCLR0

#define SYSRESET_BIT 22
#define SYSRESET_PIN IOPIN0
#define SYSRESET_DIR IODIR0
#define SYSRESET_SET IOSET0
#define SYSRESET_CLR IOCLR0

#define FPGA_LED0_BIT 0
#define FPGA_LED0_PIN FIO2PIN
#define FPGA_LED0_DIR FIO2DIR
#define FPGA_LED0_SET FIO2SET
#define FPGA_LED0_CLR FIO2CLR

#define FPGA_LED1_BIT 1
#define FPGA_LED1_PIN FIO2PIN
#define FPGA_LED1_DIR FIO2DIR
#define FPGA_LED1_SET FIO2SET
#define FPGA_LED1_CLR FIO2CLR

#define FPGA_LED2_BIT 2
#define FPGA_LED2_PIN FIO2PIN
#define FPGA_LED2_DIR FIO2DIR
#define FPGA_LED2_SET FIO2SET
#define FPGA_LED2_CLR FIO2CLR

#define FPGA_LED3_BIT 3
#define FPGA_LED3_PIN FIO2PIN
#define FPGA_LED3_DIR FIO2DIR
#define FPGA_LED3_SET FIO2SET
#define FPGA_LED3_CLR FIO2CLR

#endif //_MCB2300_H_
