IF( WIN32 )

	SET(
		CMAPI_INCLUDE_PATH
		"$ENV{ProgramFiles}/CodeMeter/Devkit/include"
	)

	SET(
		CMAPI_LIBRARY_PATH
		"$ENV{ProgramFiles}/CodeMeter/Devkit/lib"
	)

	FIND_PATH(
		CMAPI_INCLUDE_DIR
		CodeMeter.h
		${CMAPI_INCLUDE_PATH}
	)

	FIND_LIBRARY( CMAPI_32_LIBRARY NAMES WibuCm32 PATHS ${CMAPI_LIBRARY_PATH} )
	FIND_LIBRARY( CMAPI_64_LIBRARY NAMES WibuCm64 PATHS ${CMAPI_LIBRARY_PATH} )
	
ELSE( WIN32 )
	SET(
		CMAPI_INCLUDE_PATH
		"/usr/include"
	)

	SET(
		CMAPI_LIBRARY_PATH
		"/usr/lib/x86_64-linux-gnu"
	)
	
	FIND_PATH(
		CMAPI_INCLUDE_DIR
		CodeMeter.h
		${CMAPI_INCLUDE_PATH}
	)
	
	FIND_LIBRARY( CMAPI_64_LIBRARY NAMES wibucm PATHS ${CMAPI_LIBRARY_PATH} )
ENDIF( WIN32 )

SET( CMAPI_FOUND 0 )
IF( EXISTS "${CMAPI_INCLUDE_DIR}" )
	SET( CMAPI_FOUND 1 )
	INCLUDE_DIRECTORIES(
		${CMAPI_INCLUDE_DIR}
	)
ENDIF( EXISTS "${CMAPI_INCLUDE_DIR}" )
