#ifndef _ROBOTINO3IO_H_
#define _ROBOTINO3IO_H_

#ifdef MCB2300
#include "mcb2300.h"
#else

#define GPIO0_BIT 31
#define GPIO0_PIN IOPIN1
#define GPIO0_DIR IODIR1
#define GPIO0_SET IOSET1
#define GPIO0_CLR IOCLR1

#define GPIO1_BIT 12
#define GPIO1_PIN IOPIN0
#define GPIO1_DIR IODIR0
#define GPIO1_SET IOSET0
#define GPIO1_CLR IOCLR0

#define GPIO2_BIT 5
#define GPIO2_PIN FIO4PIN
#define GPIO2_DIR FIO4DIR
#define GPIO2_SET FIO4SET
#define GPIO2_CLR FIO4CLR

#define SUS_S3_BIT 25
#define SUS_S3_PIN IOPIN0
#define SUS_S3_DIR IODIR0
#define SUS_S3_SET IOSET0
#define SUS_S3_CLR IOCLR0

#define SUS_S4_BIT 5
#define SUS_S4_PIN FIO2PIN
#define SUS_S4_DIR FIO2DIR
#define SUS_S4_SET FIO2SET
#define SUS_S4_CLR FIO2CLR

#define SUS_S5_BIT 4
#define SUS_S5_PIN FIO2PIN
#define SUS_S5_DIR FIO2DIR
#define SUS_S5_SET FIO2SET
#define SUS_S5_CLR FIO2CLR

#define THRM_BIT 23
#define THRM_PIN FIO3PIN
#define THRM_DIR FIO3DIR
#define THRM_SET FIO3SET
#define THRM_CLR FIO3CLR

#define PWROK_BIT 20
#define PWROK_PIN IOPIN0
#define PWROK_DIR IODIR0
#define PWROK_SET IOSET0
#define PWROK_CLR IOCLR0

#define PWRBTN_BIT 21
#define PWRBTN_PIN IOPIN0
#define PWRBTN_DIR IODIR0
#define PWRBTN_SET IOSET0
#define PWRBTN_CLR IOCLR0

#define SYSRESET_BIT 22
#define SYSRESET_PIN IOPIN0
#define SYSRESET_DIR IODIR0
#define SYSRESET_SET IOSET0
#define SYSRESET_CLR IOCLR0

#define PROG_B_BIT 13
#define PROG_B_PIN IOPIN0
#define PROG_B_DIR IODIR0
#define PROG_B_SET IOSET0
#define PROG_B_CLR IOCLR0

#define INIT_B_BIT 2
#define INIT_B_PIN FIO2PIN
#define INIT_B_DIR FIO2DIR
#define INIT_B_SET FIO2SET
#define INIT_B_CLR FIO2CLR

#define DONE_BIT 6
#define DONE_PIN FIO2PIN
#define DONE_DIR FIO2DIR
#define DONE_SET FIO2SET
#define DONE_CLR FIO2CLR

#define ADC0_CS_BIT 29
#define ADC0_CS_PIN FIO4PIN
#define ADC0_CS_DIR FIO4DIR
#define ADC0_CS_SET FIO4SET
#define ADC0_CS_CLR FIO4CLR

#define ADC1_CS_BIT 28
#define ADC1_CS_PIN FIO4PIN
#define ADC1_CS_DIR FIO4DIR
#define ADC1_CS_SET FIO4SET
#define ADC1_CS_CLR FIO4CLR

#define SPI_CS_EXT_BIT 6
#define SPI_CS_EXT_PIN FIO4PIN
#define SPI_CS_EXT_DIR FIO4DIR
#define SPI_CS_EXT_SET FIO4SET
#define SPI_CS_EXT_CLR FIO4CLR

#define SPI_CS_OUT_BIT 7
#define SPI_CS_OUT_PIN FIO4PIN
#define SPI_CS_OUT_DIR FIO4DIR
#define SPI_CS_OUT_SET FIO4SET
#define SPI_CS_OUT_CLR FIO4CLR

#define SPI_CS_IN_BIT 8
#define SPI_CS_IN_PIN FIO4PIN
#define SPI_CS_IN_DIR FIO4DIR
#define SPI_CS_IN_SET FIO4SET
#define SPI_CS_IN_CLR FIO4CLR

#define M0_DIR_BIT 6
#define M0_DIR_PIN IOPIN0
#define M0_DIR_DIR IODIR0
#define M0_DIR_SET IOSET0
#define M0_DIR_CLR IOCLR0

#define M1_DIR_BIT 7
#define M1_DIR_PIN IOPIN0
#define M1_DIR_DIR IODIR0
#define M1_DIR_SET IOSET0
#define M1_DIR_CLR IOCLR0

#define M2_DIR_BIT 8
#define M2_DIR_PIN IOPIN0
#define M2_DIR_DIR IODIR0
#define M2_DIR_SET IOSET0
#define M2_DIR_CLR IOCLR0

#define M3_DIR_BIT 9
#define M3_DIR_PIN IOPIN0
#define M3_DIR_DIR IODIR0
#define M3_DIR_SET IOSET0
#define M3_DIR_CLR IOCLR0

#define IO_DOUT0_BIT 19
#define IO_DOUT0_PIN IOPIN1
#define IO_DOUT0_DIR IODIR1
#define IO_DOUT0_SET IOSET1
#define IO_DOUT0_CLR IOCLR1

#define IO_DOUT1_BIT 20
#define IO_DOUT1_PIN IOPIN1
#define IO_DOUT1_DIR IODIR1
#define IO_DOUT1_SET IOSET1
#define IO_DOUT1_CLR IOCLR1

#define IO_DOUT2_BIT 21
#define IO_DOUT2_PIN IOPIN1
#define IO_DOUT2_DIR IODIR1
#define IO_DOUT2_SET IOSET1
#define IO_DOUT2_CLR IOCLR1

#define IO_DOUT3_BIT 22
#define IO_DOUT3_PIN IOPIN1
#define IO_DOUT3_DIR IODIR1
#define IO_DOUT3_SET IOSET1
#define IO_DOUT3_CLR IOCLR1

#define IO_DOUT4_BIT 23
#define IO_DOUT4_PIN IOPIN1
#define IO_DOUT4_DIR IODIR1
#define IO_DOUT4_SET IOSET1
#define IO_DOUT4_CLR IOCLR1

#define IO_DOUT5_BIT 24
#define IO_DOUT5_PIN IOPIN1
#define IO_DOUT5_DIR IODIR1
#define IO_DOUT5_SET IOSET1
#define IO_DOUT5_CLR IOCLR1

#define IO_DOUT6_BIT 23
#define IO_DOUT6_PIN IOPIN0
#define IO_DOUT6_DIR IODIR0
#define IO_DOUT6_SET IOSET0
#define IO_DOUT6_CLR IOCLR0

#define IO_DOUT7_BIT 24
#define IO_DOUT7_PIN IOPIN0
#define IO_DOUT7_DIR IODIR0
#define IO_DOUT7_SET IOSET0
#define IO_DOUT7_CLR IOCLR0

#define BUMPER_BIT 28
#define BUMPER_PIN IOPIN1
#define BUMPER_DIR IODIR1
#define BUMPER_SET IOSET1
#define BUMPER_CLR IOCLR1

#endif

#endif //_ROBOTINO3IO_H_
