IF( UNIX AND NOT APPLE )
	EXECUTE_PROCESS(
		COMMAND lsb_release -a
		OUTPUT_VARIABLE CODENAMELISTSTR
		ERROR_QUIET
		TIMEOUT 10
	)
	#MESSAGE( "CODENAMELISTSTR=${CODENAMELISTSTR}" )
	STRING(REPLACE ":" " " CODENAMELISTSTR ${CODENAMELISTSTR})
	string(REGEX MATCHALL "[a-zA-Z]+" CODENAMELIST "${CODENAMELISTSTR}")
	#MESSAGE( "CODENAMELIST=${CODENAMELIST}" )
	LIST( REVERSE CODENAMELIST )
	LIST(GET CODENAMELIST 0 CODENAME )
	MESSAGE( "CODENAME=${CODENAME}" )
	IF( NOT CODENAME STREQUAL "precise"
		AND NOT CODENAME STREQUAL "trusty"
		AND NOT CODENAME STREQUAL "xenial" )
		MESSAGE( FATAL_ERROR "Unsupported CODENAME ${CODENAME}" )
	ENDIF()
ENDIF()