HEADERS += \
$$PWD/analog_input.h \
$$PWD/api1.h \
$$PWD/battery.h \
$$PWD/bumper.h \
$$PWD/camera_calibration.h \
$$PWD/camera_capabilities.h \
$$PWD/camera_control.h \
$$PWD/camera_settings.h \
$$PWD/cbha_readings.h \
$$PWD/cbha_set_compressors_enabled.h \
$$PWD/cbha_set_gripper_valve1.h \
$$PWD/cbha_set_gripper_valve2.h \
$$PWD/cbha_set_pressure.h \
$$PWD/cbha_set_water_drain_valve.h \
$$PWD/charger.h \
$$PWD/clients_connected.h \
$$PWD/current_controller.h \
$$PWD/custom_message.h \
$$PWD/digital_input.h \
$$PWD/disconnect_client.h \
$$PWD/disconnect_current_controller.h \
$$PWD/display_backlight.h \
$$PWD/display_buttons.h \
$$PWD/display_clear.h \
$$PWD/display_hbar.h \
$$PWD/display_progress.h \
$$PWD/display_text.h \
$$PWD/display_vbar.h \
$$PWD/distance_sensors.h \
$$PWD/ea09_ip4address.h \
$$PWD/ea_version.h \
$$PWD/emergency_bumper.h \
$$PWD/fleetcom_request.h \
$$PWD/grappler_readings.h \
$$PWD/grappler_servos.h \
$$PWD/grappler_set_positions.h \
$$PWD/grappler_set_power.h \
$$PWD/grappler_store_positions.h \
$$PWD/grappler_toggle_torque.h \
$$PWD/gripper_state.h \
$$PWD/gyroscope.h \
$$PWD/image.h \
$$PWD/json_message.h \
$$PWD/json_message_with_data.h \
$$PWD/kinect.h \
$$PWD/log.h \
$$PWD/map.h \
$$PWD/motor_readings.h \
$$PWD/motor_reset_position.h \
$$PWD/motor_setpoint.h \
$$PWD/northstar.h \
$$PWD/odometry.h \
$$PWD/omnidrive.h \
$$PWD/parameters.h \
$$PWD/pose.h \
$$PWD/power_button.h \
$$PWD/process.h \
$$PWD/request_shutdown.h \
$$PWD/scan.h \
$$PWD/sensors.h \
$$PWD/set_digital_output.h \
$$PWD/set_pid_parameters.h \
$$PWD/set_relay.h \
$$PWD/set_shutdown.h \
$$PWD/string_message.h
