#!/bin/sh
set -e
if [ "$1" = "upgrade" -o "$1" = "remove" ]; then
	echo Stopping services
	/etc/init.d/lcdd2.sh stop || true
	/etc/init.d/controld2.sh stop || true
	/etc/init.d/menud.sh stop || true
	/etc/init.d/rtai.sh stop || true
	killall camd2 || true
	killall ftdid || true
	killall grapplerd || true
	killall laserd2 || true
	killall srd2 || true
	killall joystickd2 || true
	killall cbhad || true
	killall robotinoxtd || true
	/etc/init.d/rpcd.sh stop || true
	killall lcdd2cmd || true
	killall controld3 || true
fi
