IF( WIN32 )
	SET( ARCH win )
ELSE( WIN32 )
	SET( ARCH linux )
ENDIF( WIN32 )

IF( CMAKE_SIZEOF_VOID_P EQUAL 8 )
  SET( ARCH ${ARCH}64 )
ELSE( CMAKE_SIZEOF_VOID_P EQUAL 8 )
  SET( ARCH ${ARCH}32 )
ENDIF( CMAKE_SIZEOF_VOID_P EQUAL 8 )

IF( NOT WIN32 )
	FIND_PATH(
		FCGI_INCLUDE_DIR 
		NAMES fastcgi.h
		PATHS ${EXTERNAL_DIR}/libfcgi/include
	)
	
	FIND_LIBRARY (
 		FCGI_LIB
		NAMES fcgi
		PATHS ${EXTERNAL_DIR}/libfcgi/lib/${ARCH}
		NO_DEFAULT_PATH
	)
ENDIF( NOT WIN32 )

SET( FCGI_FOUND 0 )

IF( FCGI_INCLUDE_DIR AND FCGI_LIB )
  SET( FCGI_FOUND 1 )
  INCLUDE_DIRECTORIES( ${FCGI_INCLUDE_DIR} )
ENDIF( FCGI_INCLUDE_DIR AND FCGI_LIB )


