#!/bin/sh
set -e

R3=0
if [ `uname -m` = "x86_64" ] ; then
  R3=1
fi

echo Stopping services

/etc/init.d/lighttpd stop

killall camd2 || true
killall ftdid || true
killall grapplerd || true
killall srd2 || true
killall joystickd2 || true
killall cbhad || true
killall robotinoxtd || true

stop rpcd || true
