#ifndef _ROBOTINO3IO_H_
#define _ROBOTINO3IO_H_

#ifdef MCB2300
#include "mcb2300.h"
#else


//**************** COM-Express signals
#define SUS_S3_BIT 31
#define SUS_S3_PIN IOPIN1
#define SUS_S3_DIR IODIR1
#define SUS_S3_SET IOSET1
#define SUS_S3_CLR IOCLR1

#define SUS_S4_BIT 4
#define SUS_S4_PIN FIO2PIN
#define SUS_S4_DIR FIO2DIR
#define SUS_S4_SET FIO2SET
#define SUS_S4_CLR FIO2CLR

#define SUS_S5_BIT 6
#define SUS_S5_PIN FIO2PIN
#define SUS_S5_DIR FIO2DIR
#define SUS_S5_SET FIO2SET
#define SUS_S5_CLR FIO2CLR

#define THRM_BIT 11
#define THRM_PIN FIO4PIN
#define THRM_DIR FIO4DIR
#define THRM_SET FIO4SET
#define THRM_CLR FIO4CLR

#define THRMTRIP_BIT 12
#define THRMTRIP_PIN FIO4PIN
#define THRMTRIP_DIR FIO4DIR
#define THRMTRIP_SET FIO4SET
#define THRMTRIP_CLR FIO4CLR

//**************** COM-Express signals

//**************** FPGA signals
#define FPGA_PROG_B_BIT 30
#define FPGA_PROG_B_PIN IOPIN1
#define FPGA_PROG_B_DIR IODIR1
#define FPGA_PROG_B_SET IOSET1
#define FPGA_PROG_B_CLR IOCLR1

#define FPGA_INIT_B_BIT 29
#define FPGA_INIT_B_PIN IOPIN1
#define FPGA_INIT_B_DIR IODIR1
#define FPGA_INIT_B_SET IOSET1
#define FPGA_INIT_B_CLR IOCLR1

#define FPGA_DONE_BIT 27
#define FPGA_DONE_PIN IOPIN1
#define FPGA_DONE_DIR IODIR1
#define FPGA_DONE_SET IOSET1
#define FPGA_DONE_CLR IOCLR1

#define FPGA_CS0_B_BIT 28
#define FPGA_CS0_B_PIN IOPIN1
#define FPGA_CS0_B_DIR IODIR1
#define FPGA_CS0_B_SET IOSET1
#define FPGA_CS0_B_CLR IOCLR1
//**************** FPGA signals

//**************** SPI signals
#define ADC0_CS_BIT 13
#define ADC0_CS_PIN FIO4PIN
#define ADC0_CS_DIR FIO4DIR
#define ADC0_CS_SET FIO4SET
#define ADC0_CS_CLR FIO4CLR

#define ADC1_CS_BIT 14
#define ADC1_CS_PIN FIO4PIN
#define ADC1_CS_DIR FIO4DIR
#define ADC1_CS_SET FIO4SET
#define ADC1_CS_CLR FIO4CLR
//**************** SPI signals

//**************** Motor signals
#define M1_DIR_BIT 19
#define M1_DIR_PIN IOPIN1
#define M1_DIR_DIR IODIR1
#define M1_DIR_SET IOSET1
#define M1_DIR_CLR IOCLR1

#define M1_ON_BIT 4
#define M1_ON_PIN FIO4PIN
#define M1_ON_DIR FIO4DIR
#define M1_ON_SET FIO4SET
#define M1_ON_CLR FIO4CLR

#define M2_DIR_BIT 20
#define M2_DIR_PIN IOPIN1
#define M2_DIR_DIR IODIR1
#define M2_DIR_SET IOSET1
#define M2_DIR_CLR IOCLR1

#define M2_ON_BIT 5
#define M2_ON_PIN FIO4PIN
#define M2_ON_DIR FIO4DIR
#define M2_ON_SET FIO4SET
#define M2_ON_CLR FIO4CLR

#define M3_DIR_BIT 21
#define M3_DIR_PIN IOPIN1
#define M3_DIR_DIR IODIR1
#define M3_DIR_SET IOSET1
#define M3_DIR_CLR IOCLR1

#define M3_ON_BIT 6
#define M3_ON_PIN FIO4PIN
#define M3_ON_DIR FIO4DIR
#define M3_ON_SET FIO4SET
#define M3_ON_CLR FIO4CLR

#define M4_DIR_BIT 22
#define M4_DIR_PIN IOPIN1
#define M4_DIR_DIR IODIR1
#define M4_DIR_SET IOSET1
#define M4_DIR_CLR IOCLR1

#define M4_ON_BIT 7
#define M4_ON_PIN FIO4PIN
#define M4_ON_DIR FIO4DIR
#define M4_ON_SET FIO4SET
#define M4_ON_CLR FIO4CLR
//**************** Motor signals

#define BUMPER_BIT 23
#define BUMPER_PIN FIO3PIN
#define BUMPER_DIR FIO3DIR
#define BUMPER_SET FIO3SET
#define BUMPER_CLR FIO3CLR

#define EXT_POWER_AKT_BIT 0
#define EXT_POWER_AKT_PIN IOPIN0
#define EXT_POWER_AKT_DIR IODIR0
#define EXT_POWER_AKT_SET IOSET0
#define EXT_POWER_AKT_CLR IOCLR0

#define BATT1_EXISTS_BIT 8
#define BATT1_EXISTS_PIN FIO4PIN
#define BATT1_EXISTS_DIR FIO4DIR
#define BATT1_EXISTS_SET FIO4SET
#define BATT1_EXISTS_CLR FIO4CLR
#define BATT1_EXISTS_PINMODE PINMODE8

#define BATT2_EXISTS_BIT 9
#define BATT2_EXISTS_PIN FIO4PIN
#define BATT2_EXISTS_DIR FIO4DIR
#define BATT2_EXISTS_SET FIO4SET
#define BATT2_EXISTS_CLR FIO4CLR
#define BATT1_EXISTS_PINMODE PINMODE8

#define BATT3_EXISTS_BIT 10
#define BATT3_EXISTS_PIN FIO4PIN
#define BATT3_EXISTS_DIR FIO4DIR
#define BATT3_EXISTS_SET FIO4SET
#define BATT3_EXISTS_CLR FIO4CLR
#define BATT1_EXISTS_PINMODE PINMODE8

//**************** MPU6000 CS
#define MPU6000_CS_BIT 15
#define MPU6000_CS_PIN FIO4PIN
#define MPU6000_CS_DIR FIO4DIR
#define MPU6000_CS_SET FIO4SET
#define MPU6000_CS_CLR FIO4CLR

//**************** Charger
#define CHARGER_NRST_BIT 27
#define CHARGER_NRST_PIN IOPIN0
#define CHARGER_NRST_DIR IODIR0
#define CHARGER_NRST_SET IOSET0
#define CHARGER_NRST_CLR IOCLR0

/*#define CHARGER_NRST_BIT 11
#define CHARGER_NRST_PIN FIO2PIN
#define CHARGER_NRST_DIR FIO2DIR
#define CHARGER_NRST_SET FIO2SET
#define CHARGER_NRST_CLR FIO2CLR*/

#define CHARGER_BOOT1_BIT 28
#define CHARGER_BOOT1_PIN IOPIN0
#define CHARGER_BOOT1_DIR IODIR0
#define CHARGER_BOOT1_SET IOSET0
#define CHARGER_BOOT1_CLR IOCLR0

#define CHARGER_BOOT2_BIT 12
#define CHARGER_BOOT2_PIN FIO2PIN
#define CHARGER_BOOT2_DIR FIO2DIR
#define CHARGER_BOOT2_SET FIO2SET
#define CHARGER_BOOT2_CLR FIO2CLR

//CHARGER_BOOT1 -> FPGA


//***************** IO
#define PWM5_BIT 24
#define PWM5_PIN IOPIN1
#define PWM5_DIR IODIR1
#define PWM5_SET IOSET1
#define PWM5_CLR IOCLR1

#define SAFTEY_BIT 5
#define SAFTEY_PIN IOPIN0
#define SAFTEY_DIR IODIR0
#define SAFTEY_SET IOSET0
#define SAFTEY_CLR IOCLR0

#define VERSION0_BIT 31
#define VERSION0_PIN FIO4PIN
#define VERSION0_DIR FIO4DIR
#define VERSION0_SET FIO4SET
#define VERSION0_CLR FIO4CLR

#define VERSION1_BIT 23
#define VERSION1_PIN IOPIN0
#define VERSION1_DIR IODIR0
#define VERSION1_SET IOSET0
#define VERSION1_CLR IOCLR0

#endif

#endif //_ROBOTINO3IO_H_
