DEFINES += rec_robotino_rpc_EXPORTS

VERSION_FILE = $$OUT_PWD/rec/robotino/rpc/rec_robotino_api2_version.h
VERSION_CONTENT = "$${LITERAL_HASH}define MajorVer 1"
VERSION_CONTENT += "$${LITERAL_HASH}define MinorVer 0"
VERSION_CONTENT += "$${LITERAL_HASH}define PatchVer 0"
VERSION_CONTENT += "$${LITERAL_HASH}define Suffix \"na\""
VERSION_CONTENT += "$${LITERAL_HASH}define BuildVer 100"
VERSION_CONTENT += "$${LITERAL_HASH}define VersionString \"100\""
write_file( $$VERSION_FILE, VERSION_CONTENT )

SOURCES += \
    $$PWD/AnalogInput.cpp \
    $$PWD/AnalogInputArray.cpp \
    $$PWD/Bumper.cpp \
    $$PWD/Camera.cpp \
    $$PWD/Charger.cpp \
    $$PWD/Client.cpp \
    $$PWD/Com.cpp \
    $$PWD/ComId.cpp \
    $$PWD/ComObject.cpp \
    $$PWD/CompactBHA.cpp \
    $$PWD/CustomMessage.cpp \
    $$PWD/DigitalInput.cpp \
    $$PWD/DigitalInputArray.cpp \
    $$PWD/DigitalOutputReader.cpp \
    $$PWD/DigitalOutput.cpp \
    $$PWD/DigitalOutputArray.cpp \
    $$PWD/DistanceSensor.cpp \
    $$PWD/DistanceSensorArray.cpp \
    $$PWD/DistanceSensorImpl.cpp \
    $$PWD/ElectricalGripper.cpp \
    $$PWD/EncoderInput.cpp \
    $$PWD/Factory4.cpp \
    $$PWD/Grappler.cpp \
    $$PWD/Gyroscope.cpp \
    $$PWD/GyroscopeExt.cpp \
    $$PWD/Kinect.cpp \
    $$PWD/LaserRangeFinder.cpp \
    $$PWD/Log.cpp \
    $$PWD/Motor.cpp \
    $$PWD/MotorArray.cpp \
    $$PWD/NorthStar.cpp \
    $$PWD/Odometry.cpp \
    $$PWD/OmniDrive.cpp \
    $$PWD/Pose.cpp \
    $$PWD/PowerButton.cpp \
    $$PWD/PowerManagement.cpp \
    $$PWD/PowerOutput.cpp \
    $$PWD/Relay.cpp \
    $$PWD/RelayArray.cpp \
    $$PWD/Shutdown.cpp \
    $$PWD/SmartCdl.cpp \
    $$PWD/CustomVis.cpp \
    $$PWD/SmartDockingVis.cpp \
    $$PWD/SmartNavigationPlanner.cpp \
    $$PWD/SmartPersonTracker.cpp \
	$$PWD/SmartLog.cpp \
    $$PWD/utils.cpp \
    $$PWD/WorkerThread.cpp
	
HEADERS += \
    $$VERSION_FILE \
    $$PWD/all.h \
    $$PWD/AnalogInput.h \
    $$PWD/AnalogInputArray.h \
    $$PWD/AnalogInputArrayImpl.hpp \
    $$PWD/AnalogInputImpl.hpp \
    $$PWD/AnalogInputReader.hpp \
    $$PWD/Bumper.h \
    $$PWD/BumperImpl.hpp \
    $$PWD/BumperReader.hpp \
    $$PWD/Camera.h \
    $$PWD/CameraCapabilities.h \
    $$PWD/CameraFormat.h \
    $$PWD/CameraImpl.hpp \
    $$PWD/CameraReader.hpp \
    $$PWD/Charger.h \
    $$PWD/ChargerImpl.hpp \
    $$PWD/ChargerReader.hpp \
    $$PWD/Client.hpp \
    $$PWD/Com.h \
    $$PWD/ComId.h \
    $$PWD/ComObject.h \
    $$PWD/ComObjectHelper.hpp \
    $$PWD/CompactBHA.h \
    $$PWD/CompactBHAImpl.hpp \
    $$PWD/CompactBHAReader.hpp \
    $$PWD/CompactBHASimple.h \
    $$PWD/CustomMessage.h \
    $$PWD/CustomMessageImpl.hpp \
    $$PWD/CustomMessageReader.hpp \
    $$PWD/defines.h \
    $$PWD/DigitalInput.h \
    $$PWD/DigitalInputArray.h \
    $$PWD/DigitalInputArrayImpl.hpp \
    $$PWD/DigitalInputImpl.hpp \
    $$PWD/DigitalInputReader.hpp \
    $$PWD/DigitalOutputReader.h \
    $$PWD/DigitalOutput.h \
    $$PWD/DigitalOutputArray.h \
    $$PWD/DigitalOutputImpl.hpp \
    $$PWD/DistanceSensor.h \
    $$PWD/DistanceSensorArray.h \
    $$PWD/DistanceSensorArrayImpl.hpp \
    $$PWD/DistanceSensorImpl.hpp \
    $$PWD/DistanceSensorsReader.hpp \
    $$PWD/ElectricalGripper.h \
    $$PWD/ElectricalGripperImpl.hpp \
    $$PWD/ElectricalGripperReader.hpp \
    $$PWD/EncoderInput.h \
    $$PWD/EncoderInputImpl.hpp \
    $$PWD/Factory4.h \
    $$PWD/Factory4Impl.hpp \
    $$PWD/Factory4JobError.h \
    $$PWD/Factory4JobInfo.h \
    $$PWD/Factory4MapInfo.h \
    $$PWD/Factory4MapList.h \
    $$PWD/Factory4McData.h \
    $$PWD/Factory4Position.h \
    $$PWD/Factory4Reader.hpp \
    $$PWD/Factory4RobotInfo.h \
    $$PWD/Grappler.h \
    $$PWD/GrapplerImpl.hpp \
    $$PWD/GrapplerReader.hpp \
    $$PWD/GrapplerReadings.h \
    $$PWD/Gyroscope.h \
    $$PWD/GyroscopeExt.h \
    $$PWD/GyroscopeExtImpl.hpp \
    $$PWD/GyroscopeExtReader.hpp \
    $$PWD/GyroscopeImpl.hpp \
    $$PWD/GyroscopeReader.hpp \
    $$PWD/JsonTopicImpl.hpp \
    $$PWD/JsonTopicReaders.hpp \
    $$PWD/Kinect.h \
    $$PWD/KinectImpl.hpp \
    $$PWD/KinectReader.hpp \
    $$PWD/LaserRangeFinder.h \
    $$PWD/LaserRangeFinderImpl.hpp \
    $$PWD/LaserRangeFinderReader.hpp \
    $$PWD/LaserRangeFinderReadings.h \
    $$PWD/LaserRangeFinderReadingsShared.h \
    $$PWD/Log.h \
    $$PWD/LogImpl.hpp \
    $$PWD/macros.hpp \
    $$PWD/Motor.h \
    $$PWD/MotorArray.h \
    $$PWD/MotorArrayImpl.hpp \
    $$PWD/MotorImpl.hpp \
    $$PWD/MotorReader.hpp \
    $$PWD/NorthStar.h \
    $$PWD/NorthStarImpl.hpp \
    $$PWD/NorthStarReader.hpp \
    $$PWD/NorthStarReadings.h \
    $$PWD/Odometry.h \
    $$PWD/OdometryImpl.hpp \
    $$PWD/OdometryReader.hpp \
    $$PWD/OmniDrive.h \
    $$PWD/OmniDriveImpl.hpp \
    $$PWD/OmniDriveModel.h \
    $$PWD/ParameterReader.hpp \
    $$PWD/Pose.h \
    $$PWD/PoseImpl.hpp \
    $$PWD/PoseReader.hpp \
    $$PWD/PowerButton.h \
    $$PWD/PowerButtonImpl.hpp \
    $$PWD/PowerButtonReader.hpp \
    $$PWD/PowerManagement.h \
    $$PWD/PowerManagementImpl.hpp \
    $$PWD/PowerManagementReader.hpp \
    $$PWD/PowerOutput.h \
    $$PWD/PowerOutputImpl.hpp \
    $$PWD/QtGrapplerReadings.h \
    $$PWD/Relay.h \
    $$PWD/RelayArray.h \
    $$PWD/RelayImpl.hpp \
    $$PWD/RobotinoException.h \
    $$PWD/Shutdown.h \
    $$PWD/SmartCdl.h \
    $$PWD/CustomVis.h \
    $$PWD/SmartDockingVis.h \
    $$PWD/SmartNavigationPlanner.h \
	$$PWD/SmartPersonTracker.h \
	$$PWD/SmartLog.h \
    $$PWD/utils.h \
    $$PWD/WorkerThread.hpp \
